### ISSUE TITLE
ログアウト機能のページ遷移について

### ISSUE THREAD

**Issue by splashkida** [splashkida/QandAsite_laravel#1]
Laravelのデフォルトの認証機能を使ってログイン・ログアウト機能を実装しています。
トップページ `resources/views/QandAsite `のヘッダー（` resources/views/layout/QandAheader `）にログインログアウトボタンを設置してるのですが、ログアウト後のページ遷移がデフォルトのdashboadに遷移してしまいます。

ログイン時のページ遷移は` app/Http/Providers/RouteServiceProvider.php ` 内の20行目を` public const HOME = 'QandAsite'; `にすることでトップへ遷移できました。

内部のページ遷移？処理？がどのように行われているのか見えずらく、どうしてこうなっているのか教えていただきたいです・・・

**Comment by splashkida** [comment]
ちなみに、使っているバージョンはLaravel 8.55.0で、
ドキュメントには

` public function logout(Request $request)
{
    Auth::logout(); `

    $request->session()->invalidate();

    $request->session()->regenerateToken();

   ` return redirect('/');
} `

↑こんな感じでかく、と書いてありました。
LogoutController.php はlaravel 8からはない？という記事もありまして、もしかして自分でコントローラを作るのでしょうか？

**Comment by tetsunosuke** [comment]
まず、現状ですが

```
% php artisan route:list | grep logout
|        | POST     | logout                           | logout                          | Laravel\Fortify\Http\Controllers\AuthenticatedSessionController@destroy         | web
```
こうなってますよね。
/logout へPOSTしていると。

で、これがそもそもFortifyってやつを使っているので、
https://laravel.com/docs/8.x/fortify#customizing-authentication-redirects これを読めばできます！

**Comment by splashkida** [comment]
おお、何故かできました！ありがとうございます！

` php artisan route:list `を実行したときに ` Action ` 欄に ` Laravel\Fortify\Http\Controllers\AuthenticatedSessionController@destroy  `とあったので` AuthenticatedSessionController `の ` destroy `アクションを実行していると思ったのですが、そもそも` AuthenticatedSessionController `がありませんでした（私の調べ方がまずいのかもしれませんが・・・）

いただいたリンクのドキュメントのコードも正直あまり理解しているとは言えませんが、Laravelを学習するにあたっては、「調べながらこういうものだと割り切って全体を浅く理解してからコードの意味などを追っていく」みたいな方がいいのでしょうか・・
