### ISSUE TITLE
MySQL DBが急にstartにならなくなった（解決しましたが何故かわかりません）

### ISSUE THREAD

**Issue by splashkida** [splashkida/QandAsite_laravel#2]
> OS mac
> XAMPP 7.2.21-1

MariaDBに ` ./mysql -u root -p ` でログインはできる状態

直前に権限の変更をいろいろ行っていたのでいろんなファイルをrootユーザーにそろえる
→変化なし

ターミナルにて` lsof -nP -i4TCP:3306 `を実行
> mysqld  7278 seirakida   21u  IPv6 0xf967f09abc7990df      0t0  TCP *:3306 (LISTEN)

と表示される
→ポート競合・・・？

` brew services list ` を実行
 > mysql@5.6 stopped 

と表示される。自動接続？設定されているものはないのかな・・・？

` ./mysql.server status `を実行
> ERROR! MariaDB is running but PID file could not be found

と表示される。

` ps -e | grep mysqld `
> 7126 ttys002    0:00.03 /bin/sh /Applications/XAMPP/xamppfiles/bin/mysqld_safe --datadir=/Applications/XAMPP/xamppfiles/var/mysql --pid-file=/Applications/XAMPP/xamppfiles/var/mysql/SEIRAnoMacBook-Air.local.pid
 7278 ttys002    0:03.89 /Applications/XAMPP/xamppfiles/sbin/mysqld --basedir=/Applications/XAMPP/xamppfiles --datadir=/Applications/XAMPP/xamppfiles/var/mysql --plugin-dir=/Applications/XAMPP/xamppfiles/lib/mysql/plugin/ --log-error=/Applications/XAMPP/xamppfiles/var/mysql/SEIRAnoMacBook-Air.local.err --pid-file=/Applications/XAMPP/xamppfiles/var/mysql/SEIRAnoMacBook-Air.local.pid --socket=/Applications/XAMPP/xamppfiles/var/mysql/mysql.sock --port=3306
18431 ttys002    0:00.01 grep mysqld

よくわからないけど、` 7278 `という処理？が邪魔しているのかもしれないと思い、

` kill 7278 `を実行
` ./mysql.server start `
> Starting MariaDB
.2021-09-03 13:41:02 18687 mysqld_safe Logging to '/Applications/XAMPP/xamppfiles/var/mysql/SEIRAnoMacBook-Air.local.err'.
2021-09-03 13:41:02 18687 mysqld_safe Starting mysqld daemon with databases from /Applications/XAMPP/xamppfiles/var/mysql
 SUCCESS! 

manager-osx のMySQL がrunning になった！
でもなぜかわかりません・・・。
今回はポート競合が原因なのでしょうか？

「MariaDBはMySQLから派生している」とあったのですが、上記のエラー中に「 MariaDB is running but PID file could not be found」とあったことから、MariaDBとMySQLは別物なのでしょうか？
また、２つのDBを使っている？というのがよくわかりません。

**Comment by tetsunosuke** [comment]
XAMPPではMariaDBがMySQLと表示されている
らしいです。なので同一と思っていて良いです。

PIDの話は今夜？にでもしますかね。

**Comment by splashkida** [comment]
そうなんですね・・・！
そういうものだと割り切るようにします。

> PIDの話は今夜？にでもしますかね。

ありがとうございます、教えてください！
23:30以降大丈夫です！

**Comment by tetsunosuke** [comment]
brew の mysqlと、xamppは別物の様子。
確かにポートは競合しうる。
どっちを起動しようとしたかと、brew servicesでの確認がどういう仕組みかについて理解する
