### ISSUE TITLE
カラムの型を変更したい

### ISSUE THREAD

**Issue by splashkida** [splashkida/QandAsite_laravel#3]
Laravel側でユニークIDを生成して記事投稿の際に` article_id `としてDBに登録させたいです。
最初、カラムの型をstring型にしていたため、下記migrationファイルを生成して、uuidに型を変更しました。
https://github.com/splashkida/QandAsite_laravel/blob/master/database/migrations/2021_09_02_080505_change_article_id_string_to_uuid_on_articles_table.php

ドキュメント通りに、` composer require doctrine/dbal `を実行し
` php artisan migrate `をしたところ、

> SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'article_id' at row 1 (SQL: ALTER TABLE articles CHANGE article_id article_id CHAR(36) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci` COMMENT '(DC2Type:guid)')

というエラーが出てしまいました。

データが長すぎるのか、文字コードが原因かと思い確認したところ、

article_id | varchar(255) | utf8mb4_unicode_ci
-- | -- | --

<br class="Apple-interchange-newline">

となっていたので文字数的には余裕があるのかと思いました。

` database.php `のファイルのmysqlの文字コードは` 'utf8mb4_unicode_ci' `となっていました。

特に問題がないような気がするのですが、何か見落としているのでしょうか・・？

**Comment by tetsunosuke** [comment]
ちょっとわからないですが、
「すでに入っているデータ」があった場合はそれの制限を受ける気がします。
データは空でしょうか？？

**Comment by splashkida** [comment]
articlesテーブルにデータは既に入っている状態です。

**Comment by splashkida** [comment]
データを消したらmigrateできました・・・！
