### ISSUE TITLE
phpmyadmin上のエラーについて

### ISSUE THREAD

**Issue by splashkida** [splashkida/QandAsite_laravel#4]
<img width="1234" alt="スクリーンショット 2021-09-03 15 04 52" src="https://user-images.githubusercontent.com/71440835/131959979-f3823c59-7331-4239-a223-03e2649f16a1.png">

上の画像の下部に2つエラーが出ています。
現場、特に問題が起こっているわけではないのですが、できれば解決できればいいなと考えております。

したのエラーは` /Applications/XAMPP/xamppfiles/phpmyadmin/tmp/ `にアクセスできないので、権限のエラーだと思いました。

【試したこと】
`  /Applications/XAMPP/xamppfiles/phpmyadmin/ `へ移動して権限を下記のように変更しました。
> drwxrwxr-x   3 root  admin      96  7 29 14:14 tmp

` config.inc.php `の権限は root:adminで内容は、

> /* Authentication type */
$cfg['Servers'][$i]['auth_type'] = 'config';
$cfg['Servers'][$i]['user'] = 'root';
$cfg['Servers'][$i]['password'] = '設定したPW';

になっています。

権限を揃えればいいものだと思っていたので、なぜアクセスできないのか疑問です。
（rootユーザーはすべての権限を持つのでrootに揃えようと思いました）

**Comment by splashkida** [comment]
上の` phpMyAdmin 環境保管領域が完全に設定されていないため、いくつかの拡張機能が無効になっています。理由についてはこちらをご覧ください。 
代わりにデータベースの操作タブを使って設定することもできます。 `

というエラーはなぜ起こっているかわかりませんが、下記のことを試しました。


【試したこと】
1. phpmyadminで` \xampp\phpMyAdmin\sql\create_tables.sql `をインポート
2. ` /Applications/XAMPP/xamppfiles/phpmyadmin/config.inc.php ` のコメントアウトを外す。（もともと外れていました）

/* Storage database and tables */
$cfg['Servers'][$i]['pmadb'] = 'phpmyadmin';
$cfg['Servers'][$i]['bookmarktable'] = 'pma__bookmark';
$cfg['Servers'][$i]['relation'] = 'pma__relation';
$cfg['Servers'][$i]['table_info'] = 'pma__table_info';
$cfg['Servers'][$i]['table_coords'] = 'pma__table_coords';
$cfg['Servers'][$i]['pdf_pages'] = 'pma__pdf_pages';
$cfg['Servers'][$i]['column_info'] = 'pma__column_info';
$cfg['Servers'][$i]['history'] = 'pma__history';
$cfg['Servers'][$i]['table_uiprefs'] = 'pma__table_uiprefs';
$cfg['Servers'][$i]['tracking'] = 'pma__tracking';
$cfg['Servers'][$i]['userconfig'] = 'pma__userconfig';
$cfg['Servers'][$i]['recent'] = 'pma__recent';
$cfg['Servers'][$i]['users'] = 'pma__users';
$cfg['Servers'][$i]['usergroups'] = 'pma__usergroups';
$cfg['Servers'][$i]['navigationhiding'] = 'pma__navigationhiding';
$cfg['Servers'][$i]['savedsearches'] = 'pma__savedsearches';
$cfg['Servers'][$i]['central_columns'] = 'pma__central_columns';
$cfg['Servers'][$i]['designer_coords'] = 'pma__designer_coords';
$cfg['Servers'][$i]['designer_settings'] = 'pma__designer_settings';
$cfg['Servers'][$i]['export_templates'] = 'pma__export_templates';
$cfg['Servers'][$i]['favorite'] = 'pma__favorite';
// $cfg['Servers'][$i]['favorite'] = 'pma__favorite';
// $cfg['Servers'][$i]['users'] = 'pma__users';
// $cfg['Servers'][$i]['usergroups'] = 'pma__usergroups';
// $cfg['Servers'][$i]['navigationhiding'] = 'pma__navigationhiding';
// $cfg['Servers'][$i]['savedsearches'] = 'pma__savedsearches';
// $cfg['Servers'][$i]['central_columns'] = 'pma__central_columns';
// $cfg['Servers'][$i]['designer_settings'] = 'pma__designer_settings';
// $cfg['Servers'][$i]['export_templates'] = 'pma__export_templates';

↑重複しているものだけデフォルトで` // `が入っていたので特に触る必要がなかったです。


これでエラーが解決できるとのことですが、特に変わらずでした・・・

お手隙の際にでもご確認いただけたら嬉しいです！
どうぞよろしくお願いたします。

**Comment by tetsunosuke** [comment]
こちらは多分pmaユーザ関連の確認（後ほど）
